      $(function()
        {
            $("#MoveMe1").draggable();
            $("#MoveMe2").draggable();
            $("#MoveMe3").draggable();
            $("#MoveMe4").draggable();
            $("#MoveMe5").draggable();
            $("#MoveMe6").draggable();
            $("#MoveMe7").draggable();
            $("#MoveMe8").draggable();
            $("#MoveMe9").draggable();
        });